# 1. Create a Numpy array of size 4 x 5.

In [3]:
import numpy as np
x = np.array([[1,1,2,3,4],[7,5,6,4,8],[4,1,7,3,2],[4,1,6,3,8]])
print(x)

[[1 1 2 3 4]
 [7 5 6 4 8]
 [4 1 7 3 2]
 [4 1 6 3 8]]


# 2. Randomly initialize the array.

In [7]:
y=np.random.rand(3,2)
print(y)

[[0.84405081 0.05837376]
 [0.12194268 0.69571888]
 [0.72050237 0.80126291]]


# 3. Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [4]:
x = np.array([[1,1,2,3,4],[7,5,6,4,8],[4,1,7,3,2],[4,1,6,3,8],[4,9,6,7,8]])
# only square matrix allowed
dett = np.linalg.det(x)
print(int(dett))

# transpose of matrix
z = x.transpose()
print(z)

-1520
[[1 7 4 4 4]
 [1 5 1 1 9]
 [2 6 7 6 6]
 [3 4 3 3 7]
 [4 8 2 8 8]]


# 4. Create another matrix of size 5 x 4 and randomly initialize it.

In [2]:
import numpy as np
mat4 = np.random.rand(5,4)
print("Array initialized with Random value :\n",mat4)

Array initialized with Random value :
 [[0.72916849 0.91402765 0.7435103  0.7286343 ]
 [0.98162536 0.66169129 0.11650891 0.9828324 ]
 [0.36881613 0.44801243 0.39615633 0.84938638]
 [0.34206971 0.56952341 0.95948167 0.88530499]
 [0.21648354 0.52619391 0.23921044 0.43735275]]


# 5. Perform Matrix multiplication.

In [4]:
p = np.array([[0,1,2,3,4],[4,3,6,9,8],[4,5,3,3,4],[4,7,9,7,8]])
q = np.array([[2,9,6,3],[3,2,10,8],[2,1,6,9],[7,9,6,9],[10,3,5,2]])
print(np.dot(p,q))
print('\n')
# @ method
print(p@q)

[[ 68  43  60  61]
 [172 153 184 187]
 [ 90  88 130 114]
 [176 146 230 228]]


[[ 68  43  60  61]
 [172 153 184 187]
 [ 90  88 130 114]
 [176 146 230 228]]


# 6. Perform element wise matrix multiplication.

In [5]:
p = np.array([[0,1,2,3,4],[4,3,6,9,8],[4,5,3,3,4],[4,7,9,7,8]])
q = np.array([[2,9,6,3,6],[3,2,10,8,8],[2,1,6,9,2],[7,9,6,9,7]])
print(np.multiply(p,q))

[[ 0  9 12  9 24]
 [12  6 60 72 64]
 [ 8  5 18 27  8]
 [28 63 54 63 56]]


# 7. Find mean, median of the numpy array created.

In [6]:
w = np.array([17,11,24,37,39,71])
# median of 1D array
print(np.median(w))

# mean of 1D arary
print(np.mean(w))

30.5
33.166666666666664


# 8. Obtain each row in the second column of the first array.

In [19]:
print(p[0:,1])

[1 3 5 7]


# 9. Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [8]:
import pandas as pd
iris=pd.read_csv('iris.csv')
print(iris.mean())

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64


# 10. Study about numpy array attributes and implement it on the first matrix.

In [22]:
import numpy as np
a = np.array([[7,1,2,3,9],[5,3,7,3,2]]) 
print(a.shape)
b = a.reshape(5,2)
print(b)

(2, 5)
[[7 1]
 [2 3]
 [9 5]
 [3 7]
 [3 2]]
