**AIM : Implement Linear Regression Algorithm on the given dataset.**

**Exercise 1: Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn.**

In [1]:
import numpy as np
import torch

In [2]:
#Input (Temp, Rainfall, Humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

#Target (Apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

#Converting inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
#Weights and Biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights : \n", w)
print("\nBiases : \n", b)

Weights : 
 tensor([[-0.8250,  1.3650, -0.2997]], requires_grad=True)

Biases : 
 tensor([-1.1576], requires_grad=True)


In [4]:
#Defining the model
def model(x):
    return  torch.mm(x, w.t(), out=None) + b

In [5]:
#Generating Predictions
preds = model(inputs)

#Comparing Predictions with targets
print("Predictions : \n", preds)
print("\nTargets : \n", targets)

Predictions : 
 tensor([[ 17.1802],
        [ 24.7002],
        [ 92.5865],
        [-37.7069],
        [ 51.9726]], grad_fn=<AddBackward0>)

Targets : 
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [6]:
#Defining MSE loss function
def MSELoss(P, T): 
  sum = 0
  n = len(T)
  for j in range(0, n):
    sum += (T[j] - P[j]) * (T[j] - P[j])
  return sum / n

loss = MSELoss(preds, targets)
print("MSE Loss : ", loss[0])    

MSE Loss :  tensor(2308.6047, grad_fn=<SelectBackward0>)


In [7]:
#Computing Gradient
loss.backward()
print("Gradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)


Gradients for weights : 
 tensor([[-7946.4375, -7424.2969, -5034.1968]])

Gradient for biases: 
 tensor([-92.9070])


In [8]:
#Adjusting weights and biases using Gradient Descent
#Reseting gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print("Gradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)

print("\nNew Weights : \n", w)
print("\nNew Biases : \n", b)

Gradients for weights : 
 tensor([[0., 0., 0.]])

Gradient for biases: 
 tensor([0.])

New Weights : 
 tensor([[-0.7456,  1.4392, -0.2493]], requires_grad=True)

New Biases : 
 tensor([-1.1567], requires_grad=True)


In [9]:
#Calculating  new loss
preds = model(inputs)

loss = MSELoss(preds, targets)
print("New MSE Loss : ", loss[0])  

New MSE Loss :  tensor(1128.6193, grad_fn=<SelectBackward0>)


In [10]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MSELoss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss[0])  

MSE Loss :  tensor(80.8520, grad_fn=<SelectBackward0>)


**Exercise 2: Try Linear regression on same prediction data using Tensorflow**

In [11]:
import torch.nn as nn

In [12]:
#Input (Temp, Rainfall, Humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

#Target (Apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

#Converting inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [13]:
#Weights and Biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights : \n", w)
print("\nBiases : \n", b)

Weights : 
 tensor([[0.3567, 1.8210, 0.2669]], requires_grad=True)

Biases : 
 tensor([0.6189], requires_grad=True)


In [14]:
#Defining the model
def model(x):
    return  x @ w.t() + b

In [15]:
#Generating Predictions
preds = model(inputs)

#Comparing Predictions with targets
print("Predictions : \n", preds)
print("\nTargets : \n", targets)

Predictions : 
 tensor([[160.1391],
        [210.4048],
        [291.1433],
        [125.1769],
        [218.7275]], grad_fn=<AddBackward0>)

Targets : 
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [17]:
MSELoss = nn.MSELoss()
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss) 

MSE Loss :  tensor(16252.4375, grad_fn=<MseLossBackward0>)


In [18]:

#Computing Gradient
loss.backward()
print("\nGradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)


Gradients for weights : 
 tensor([[21145.4805, 22791.4375, 13865.0693]])

Gradient for biases: 
 tensor([249.8366])


In [19]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MSELoss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss)

MSE Loss :  tensor(51.9856, grad_fn=<MseLossBackward0>)
